### ISSUE TITLE
struct functionPointersPortB 

### ISSUE THREAD

**Issue by arjunmehta94** [GreyGnome/EnableInterrupt#1]
Hello, I get the following error when I try to compile the code. Can you please provide some guidance on this?

In file included from Interrupt.ino:1:
/Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h: In function 'void __vector_3()':
/Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h:976: error: 'struct functionPointersPortB' has no member named 'pinSix'
/Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h:977: error: 'struct functionPointersPortB' has no member named 'pinSeven'

**Comment by GreyGnome** [comment]
Sorry about that. Which Arduino are you using?

I will take a look at it.

**Comment by arjunmehta94** [comment]
I am using the Uno.

**Comment by GreyGnome** [comment]
I added some #ifndef so the problem pins are not attempted to be compiled.
Odd that I didn't see that problem in my testing.

Could you grab the EnableInterrupt.h file from the Github site and give it
a test?

On Fri, Apr 10, 2015 at 3:01 AM, Arjun Mehta notifications@github.com
wrote:

> Hello, I get the following error when I try to compile the code. Can you
> please provide some guidance on this?
> 
> In file included from Interrupt.ino:1:
> /Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h:
> In function 'void __vector_3()':
> /Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h:976:
> error: 'struct functionPointersPortB' has no member named 'pinSix'
> /Users/arjunmehta94/Documents/Arduino/libraries/EnableInterrupt-master/EnableInterrupt.h:977:
> error: 'struct functionPointersPortB' has no member named 'pinSeven'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GreyGnome/EnableInterrupt/issues/1.

## 

-Mike Schwager

**Comment by GreyGnome** [comment]
30 days; autoclose.
