### ISSUE TITLE
library.properties a little out dated

### ISSUE THREAD

**Issue by stickbreaker** [GreyGnome/EnableInterrupt#17]
version=0.6.0 should be 0.8.1 :smiley: 
architectures=\* could be avr :smiley: 
paragraph= is kind of strange? 'Provides a ponsistent API'? :confused: 

Chuck.

**Comment by GreyGnome** [comment]
Thanks, I'm going to post 0.8.2 soon and I will include these fixes. I'm also going to include a checklist to remember to update that file! And a spellchecker... :-)
