### ISSUE TITLE
Using PORTB interrupts on ATtiny84

### ISSUE THREAD

**Issue by rtlr** [GreyGnome/EnableInterrupt#29]
Pin change interrupts set on B0 and B1 were failing to trigger the appropriate functions.

Adding the following to the code directs mask to the right register and appears to solve the issue:
# ifdef EI_ATTINY24

  interruptMask = PCMSK1 & interruptMask;
...
# ENDIF

**Comment by GreyGnome** [comment]
Thanks. It's a holiday weekend, so I'll take a look at this soon but I'm kind of busy putting up Christmas decorations :-) .

**Comment by GreyGnome** [comment]
It's been out a while. I'll close this.
