### ISSUE TITLE
Compatibility with Arduino IDE library manager

### ISSUE THREAD

**Issue by jan-van** [GreyGnome/EnableInterrupt#5]
Nice Lib. I had to move around the folders and files a little before my sketch compiled.
The current version of the Arduino IDE (1.6.4) has a standardised method to include external libraries.
By default it places the files from a ZIP file into a directory under the MyDocuments/Arduino folder.

When included using the libarary manager, it expects the header file to be included in the top folder of the libary file, and that header file is then inserted in the source of the sketch. Thus it requires the "EnableInterrupt.h" to be moved to the top folder of the ZIP file. Only the file to be included in the sketch is needed since all .h files found in the top folder are inserted in the sketch source. The description is currently not visible in the list within the IDE.

A manual on how to organise external libraries is documented on http://www.arduino.cc/en/Guide/Libraries

**Comment by GreyGnome** [comment]
Thanks, I'll look into it.

On Sat, May 30, 2015 at 5:41 PM, jan-van notifications@github.com wrote:

> Nice Lib. I had to move around the folders and files a little before my
> scetch compiled.
> The current version of the Arduino IDE (1.6.4) has a standardised method
> to include external libraries.
> By default it places the files from a ZIP file into a directory under the
> MyDocuments/Arduino folder.
> 
> When included using the libarary manager, it expects the header file to be
> included in the top folder of the libary file, and that header file is then
> inserted in the source of the sketch. Thus it requires the
> "EnableInterrupt.h" to be moved to the top folder of the ZIP file. Only the
> file to be included in the sketch is needed since all .h files found in the
> top folder are inserted in the sketch source. The description is currently
> not visible in the list within the IDE.
> 
> A manual on how to organise external libraries is documented on
> http://www.arduino.cc/en/Guide/Libraries
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GreyGnome/EnableInterrupt/issues/5.

## 

-Mike Schwager

**Comment by GreyGnome** [comment]
I'm working on this now.

**Comment by GreyGnome** [comment]
The library is in the Library Manager. It looks good to me... let me know if you have any further issues.

Thanks for the suggestion.
