### ISSUE TITLE
New release to make the removal of the pragma "official"

### ISSUE THREAD

**Issue by SRGDamia1** [GreyGnome/EnableInterrupt#59]
Any chance you could do another release to force the library registries to pick up the change to the pragma message?  I think this library is wonderful and use it all the time so it would be nice to stop seeing the outdated pragma with every build.

Thanks!

**Comment by GreyGnome** [comment]
OK sorry about that. I need to delete that thing entirely, it seems to me. I'll take care of it.

**Comment by SRGDamia1** [comment]
Thank you!

**Comment by GreyGnome** [comment]
Done. Version 1.1.0 is out.
