### ISSUE TITLE
How I can use enableInterrupt in class

### ISSUE THREAD

**Issue by k-samsonov** [GreyGnome/EnableInterrupt#6]
// Test.h
# ifndef _TEST_h
# define _TEST_h
# if defined(ARDUINO) && ARDUINO >= 100

```
#include "arduino.h"
```
# else

```
#include "WProgram.h"
```
# endif
# define ADC_EXTERNAL_PIN 2
# include <EnableInterrupt.h>

class TestClass
{
 protected:
  interruptFunctionType pInt;

 public:
  TestClass();
    void init();
  void start();
  void stop();
  static void _interruptFunction();
};
# endif

// Test.cpp
# include "Test.h"

void TestClass::init()
{

  pInt = static_cast<interruptFunctionType>( TestClass::_interruptFunction);
}

  void TestClass::start()
  {
    enableInterrupt (ADC_EXTERNAL_PIN,  pInt  , FALLING);  
  }
  void TestClass::stop()
  {
    disableInterrupt (ADC_EXTERNAL_PIN);  
  }

this code not compiled

**Comment by NicoHood** [comment]
I've removed this text because it does not address the user's question: How to use enableInterrupt in a class. 

Likewise, I've modified my next answer and removed the analysis of the EnableInterrupt and Nico's Pin Change interrupt library. We can discuss the merits and pro's/con's in a forum somewhere. This is for issues and answers with this library.
- GreyGnome

**Comment by GreyGnome** [comment]
Essentially you want to mix C and C++. The answer lurks somewhere in here: https://isocpp.org/wiki/faq/mixing-c-and-cpp

On my todo list is to create some sample code that folks can use as a template. In short: I know what you're trying to do, it's a good idea, it can be done. Expect a more complete answer in a week or so.

**Comment by GreyGnome** [comment]
I have created a new release and it now includes an example, OOSimple.ino. Check it out.

Briefly, you are mixing C and C++, and the EnableInterrupt library is C code. So set up the interrupts in C, and have it call a C++ method in an object. You can then perform other logic in the C++ code, but largely the interrupt library is managed mostly in C (in my example).

It looks like it's pretty easy to enable the interrupt from the C++ object. See http://stackoverflow.com/questions/16850992/call-a-c-function-from-c-code, or, of course, Google. I'll leave the details of that as an exercise for the reader :-) .

**Comment by GreyGnome** [comment]
The example is written and tested. This issue is closed.
